// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "MedCore Team",
            "email": "support@medcore.local"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authentifie un utilisateur MedCore et retourne un JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Connexion utilisateur",
                "parameters": [
                    {
                        "description": "Identifiants utilisateur",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/openapi.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/consultations": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consultations"
                ],
                "summary": "Créer une consultation médicale",
                "parameters": [
                    {
                        "description": "Consultation",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consultations.CreateConsultationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/consultations.Consultation"
                        }
                    }
                }
            }
        },
        "/consultations/exams": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consultations"
                ],
                "summary": "Liste des examens médicaux",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/consultations.MedicalExam"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consultations - Référentiels"
                ],
                "summary": "Créer un examen médical",
                "parameters": [
                    {
                        "description": "Examen",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consultations.CreateReferenceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/consultations.MedicalExam"
                        }
                    }
                }
            }
        },
        "/consultations/exams/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Modifie les informations d'un examen médical du référentiel. Permission requise : consultations.references.manage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consultations - Référentiels"
                ],
                "summary": "Modifier un examen médical",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'examen",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Données de l'examen",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consultations.UpdateReferenceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consultations.MedicalExam"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Désactive un examen médical du référentiel. Permission requise : consultations.references.manage.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consultations - Référentiels"
                ],
                "summary": "Désactiver un examen médical",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'examen",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/consultations/reasons": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consultations"
                ],
                "summary": "Liste des motifs de consultation",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/consultations.ConsultationReason"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consultations - Référentiels"
                ],
                "summary": "Créer un motif de consultation",
                "parameters": [
                    {
                        "description": "Motif",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consultations.CreateReferenceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/consultations.ConsultationReason"
                        }
                    }
                }
            }
        },
        "/consultations/reasons/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consultations - Référentiels"
                ],
                "summary": "Modifier un motif de consultation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID motif",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Motif",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consultations.UpdateReferenceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consultations - Référentiels"
                ],
                "summary": "Désactiver un motif de consultation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID motif",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/consultations/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consultations"
                ],
                "summary": "Détail d'une consultation médicale",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID consultation",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consultations.Consultation"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consultations"
                ],
                "summary": "Modifier une consultation médicale",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID consultation",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Consultation",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consultations.UpdateConsultationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consultations.Consultation"
                        }
                    }
                }
            }
        },
        "/consultations/{id}/exam-request/pdf": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "Documents médicaux"
                ],
                "summary": "Générer la demande d'examens",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID consultation",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/consultations/{id}/hospitalization/pdf": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "Documents médicaux"
                ],
                "summary": "Générer la fiche d'hospitalisation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID consultation",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/consultations/{id}/prescription/pdf": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "Documents médicaux"
                ],
                "summary": "Générer l'ordonnance",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID consultation",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/consultations/{id}/report/pdf": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "Documents médicaux"
                ],
                "summary": "Générer le compte rendu de consultation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID consultation",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/consultations/{id}/sick-leave/pdf": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Génère la fiche PDF de repos maladie prescrite lors d'une consultation.",
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "Documents médicaux"
                ],
                "summary": "Générer la fiche de repos maladie",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la consultation",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/consultations/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consultations"
                ],
                "summary": "Changer le statut d'une consultation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID consultation",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Statut",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/consultations.UpdateConsultationStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consultations.Consultation"
                        }
                    }
                }
            }
        },
        "/insurance/companies": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne la liste des compagnies d'assurance.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Insurance Companies"
                ],
                "summary": "Lister les compagnies d'assurance",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/openapi.SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crée une nouvelle compagnie d'assurance.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Insurance Companies"
                ],
                "summary": "Créer une compagnie d'assurance",
                "parameters": [
                    {
                        "description": "Données compagnie",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/company.CreateCompanyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/openapi.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/insurance/companies/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne les informations d’une compagnie d'assurance par son ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Insurance Companies"
                ],
                "summary": "Détail compagnie d'assurance",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID compagnie d'assurance",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/openapi.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour les informations d’une compagnie d'assurance existante.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Insurance Companies"
                ],
                "summary": "Modifier une compagnie d'assurance",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID compagnie d'assurance",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Données compagnie d'assurance",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/company.UpdateCompanyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/openapi.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Supprime une compagnie d'assurance par son ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Insurance Companies"
                ],
                "summary": "Supprimer une compagnie d'assurance",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID compagnie d'assurance",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/openapi.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/patients": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crée un nouveau patient dans MedCore.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patients"
                ],
                "summary": "Créer un patient",
                "parameters": [
                    {
                        "description": "Données patient",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/patients.CreatePatientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/openapi.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/patients/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne les informations d’un patient par son ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patients"
                ],
                "summary": "Détail patient",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID patient",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/openapi.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour les informations d’un patient existant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patients"
                ],
                "summary": "Modifier un patient",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID patient",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Données patient",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/patients.UpdatePatientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/openapi.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Supprime un patient par son ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patients"
                ],
                "summary": "Supprimer un patient",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID patient",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/openapi.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/openapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/patients/{id}/360": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient 360"
                ],
                "summary": "Vue Patient 360",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID patient",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/consultations.Patient360Response"
                        }
                    }
                }
            }
        },
        "/patients/{id}/consultations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne toutes les consultations médicales du patient avec motifs, constantes, examens et prescriptions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient 360"
                ],
                "summary": "Historique des consultations d'un patient",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID du patient",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/consultations.Consultation"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 4
                }
            }
        },
        "company.CreateCompanyRequest": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string",
                    "maxLength": 100
                },
                "code": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "country": {
                    "type": "string",
                    "maxLength": 100
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "maxLength": 150
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 2
                },
                "phone": {
                    "type": "string",
                    "maxLength": 50
                }
            }
        },
        "company.UpdateCompanyRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string",
                    "maxLength": 100
                },
                "code": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "country": {
                    "type": "string",
                    "maxLength": 100
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "maxLength": 150
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 2
                },
                "phone": {
                    "type": "string",
                    "maxLength": 50
                }
            }
        },
        "consultations.Consultation": {
            "type": "object",
            "properties": {
                "cancellationReason": {
                    "type": "string"
                },
                "cancelledAt": {
                    "type": "string"
                },
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "diagnosis": {
                    "type": "string"
                },
                "doctorName": {
                    "type": "string"
                },
                "exams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/consultations.MedicalExam"
                    }
                },
                "hospitalizationDuration": {
                    "type": "integer"
                },
                "hospitalizationReason": {
                    "type": "string"
                },
                "hospitalizationRequired": {
                    "type": "boolean"
                },
                "hospitalizationType": {
                    "description": "medicale / chirurgicale",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "observations": {
                    "type": "string"
                },
                "patient": {
                    "$ref": "#/definitions/patients.Patient"
                },
                "patientId": {
                    "type": "integer"
                },
                "prescriptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/consultations.ConsultationPrescription"
                    }
                },
                "reasons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/consultations.ConsultationReason"
                    }
                },
                "service": {
                    "type": "string"
                },
                "sickLeaveDays": {
                    "type": "integer"
                },
                "sickLeaveEndDate": {
                    "type": "string"
                },
                "sickLeaveRequired": {
                    "type": "boolean"
                },
                "sickLeaveStartDate": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "treatment": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "vitals": {
                    "$ref": "#/definitions/consultations.ConsultationVitals"
                }
            }
        },
        "consultations.ConsultationPrescription": {
            "type": "object",
            "properties": {
                "consultationId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "dosage": {
                    "type": "string"
                },
                "duration": {
                    "type": "string"
                },
                "form": {
                    "type": "string"
                },
                "frequency": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "instructions": {
                    "type": "string"
                },
                "medicationName": {
                    "type": "string"
                },
                "route": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "consultations.ConsultationReason": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "consultations.ConsultationVitals": {
            "type": "object",
            "properties": {
                "bloodGlucose": {
                    "type": "number"
                },
                "bloodPressureDiastolic": {
                    "type": "integer"
                },
                "bloodPressureSystolic": {
                    "type": "integer"
                },
                "consultationId": {
                    "type": "integer"
                },
                "heartRate": {
                    "type": "integer"
                },
                "height": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "oxygenSaturation": {
                    "type": "integer"
                },
                "painScore": {
                    "type": "integer"
                },
                "respiratoryRate": {
                    "type": "integer"
                },
                "temperature": {
                    "type": "number"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "consultations.ConsultationVitalsRequest": {
            "type": "object",
            "properties": {
                "bloodGlucose": {
                    "type": "number"
                },
                "bloodPressureDiastolic": {
                    "type": "integer"
                },
                "bloodPressureSystolic": {
                    "type": "integer"
                },
                "heartRate": {
                    "type": "integer"
                },
                "height": {
                    "type": "number"
                },
                "oxygenSaturation": {
                    "type": "integer"
                },
                "painScore": {
                    "type": "integer"
                },
                "respiratoryRate": {
                    "type": "integer"
                },
                "temperature": {
                    "type": "number"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "consultations.CreateConsultationRequest": {
            "type": "object",
            "required": [
                "doctorName",
                "patientId"
            ],
            "properties": {
                "diagnosis": {
                    "type": "string"
                },
                "doctorName": {
                    "type": "string"
                },
                "examIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "hospitalizationDuration": {
                    "type": "integer"
                },
                "hospitalizationReason": {
                    "type": "string"
                },
                "hospitalizationRequired": {
                    "type": "boolean"
                },
                "hospitalizationType": {
                    "type": "string"
                },
                "observations": {
                    "type": "string"
                },
                "patientId": {
                    "type": "integer"
                },
                "prescriptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/consultations.PrescriptionRequest"
                    }
                },
                "reasonIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "service": {
                    "type": "string"
                },
                "sickLeaveDays": {
                    "type": "integer"
                },
                "sickLeaveRequired": {
                    "type": "boolean"
                },
                "treatment": {
                    "type": "string"
                },
                "vitals": {
                    "$ref": "#/definitions/consultations.ConsultationVitalsRequest"
                }
            }
        },
        "consultations.CreateReferenceRequest": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "consultations.MedicalExam": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "consultations.Patient360Response": {
            "type": "object",
            "properties": {
                "consultations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/consultations.Consultation"
                    }
                },
                "documents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/consultations.PatientDocumentItem"
                    }
                },
                "patientId": {
                    "type": "integer"
                }
            }
        },
        "consultations.PatientDocumentItem": {
            "type": "object",
            "properties": {
                "consultationId": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "consultations.PrescriptionRequest": {
            "type": "object",
            "required": [
                "medicationName"
            ],
            "properties": {
                "dosage": {
                    "type": "string"
                },
                "duration": {
                    "type": "string"
                },
                "form": {
                    "type": "string"
                },
                "frequency": {
                    "type": "string"
                },
                "instructions": {
                    "type": "string"
                },
                "medicationName": {
                    "type": "string"
                },
                "route": {
                    "type": "string"
                }
            }
        },
        "consultations.UpdateConsultationRequest": {
            "type": "object",
            "properties": {
                "diagnosis": {
                    "type": "string"
                },
                "doctorName": {
                    "type": "string"
                },
                "examIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "hospitalizationDuration": {
                    "type": "integer"
                },
                "hospitalizationReason": {
                    "type": "string"
                },
                "hospitalizationRequired": {
                    "type": "boolean"
                },
                "hospitalizationType": {
                    "type": "string"
                },
                "observations": {
                    "type": "string"
                },
                "prescriptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/consultations.PrescriptionRequest"
                    }
                },
                "reasonIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "service": {
                    "type": "string"
                },
                "sickLeaveDays": {
                    "type": "integer"
                },
                "sickLeaveRequired": {
                    "type": "boolean"
                },
                "treatment": {
                    "type": "string"
                },
                "vitals": {
                    "$ref": "#/definitions/consultations.ConsultationVitalsRequest"
                }
            }
        },
        "consultations.UpdateConsultationStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "cancellationReason": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "consultations.UpdateReferenceRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "openapi.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "openapi.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/openapi.ErrorDetail"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "openapi.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "meta": {},
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "patients.CreatePatientRequest": {
            "type": "object",
            "required": [
                "nom"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "maximum": 130,
                    "minimum": 0
                },
                "dateNaissance": {
                    "type": "string"
                },
                "isAssure": {
                    "type": "boolean"
                },
                "matriculeAssure": {
                    "type": "string",
                    "maxLength": 100
                },
                "nom": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "personneContact": {
                    "type": "string",
                    "maxLength": 150
                },
                "prenoms": {
                    "type": "string",
                    "maxLength": 150
                },
                "quartier": {
                    "type": "string",
                    "maxLength": 150
                },
                "sexe": {
                    "type": "string",
                    "enum": [
                        "M",
                        "F"
                    ]
                },
                "tauxCouverture": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0
                },
                "telephone": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 8
                }
            }
        },
        "patients.Patient": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "codePatient": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer"
                },
                "dateNaissance": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isAssure": {
                    "type": "boolean"
                },
                "matriculeAssure": {
                    "type": "string"
                },
                "nom": {
                    "type": "string"
                },
                "numeroDossier": {
                    "type": "string"
                },
                "personneContact": {
                    "type": "string"
                },
                "prenoms": {
                    "type": "string"
                },
                "quartier": {
                    "type": "string"
                },
                "sexe": {
                    "type": "string"
                },
                "tauxCouverture": {
                    "type": "number"
                },
                "telephone": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "patients.UpdatePatientRequest": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "dateNaissance": {
                    "type": "string"
                },
                "isAssure": {
                    "type": "boolean"
                },
                "matriculeAssure": {
                    "type": "string"
                },
                "nom": {
                    "type": "string"
                },
                "personneContact": {
                    "type": "string"
                },
                "prenoms": {
                    "type": "string"
                },
                "quartier": {
                    "type": "string"
                },
                "sexe": {
                    "type": "string"
                },
                "tauxCouverture": {
                    "type": "number"
                },
                "telephone": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Bearer token. Exemple : Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "medcore-his-api-latest.onrender.com",
	BasePath:         "/api",
	Schemes:          []string{"https"},
	Title:            "MedCore HIS API",
	Description:      "Modern Hospital Information System API\nModules disponibles : Auth, Patients, Insurance, Workflow, Audit.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
